# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: xenial

cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm


latex: false
branches:
  only:
    - master
    - devel

pandoc_version: 2.9.2

git:
  depth: 5
  submodules: false

repos:
  CRAN: https://cloud.r-project.org

addons:
  apt:
    packages:
      - ghostscript
      - imagemagick
      - optipng

before_install:
  # TinyTeX
  - Rscript -e 'install.packages("tinytex"); tinytex:::install_prebuilt()'
  - export PATH=$HOME/bin:$PATH
  - tlmgr install hyphen-german elegantbook ctex ttfutils xecjk zhnumber listings
      cancel kastrup anyfontsize esint jknapltx mdwtools
      multirow makecell gbt7714 xpatch pgfornament pgfopts mwe hologo
      apptools manfnt bbding tcolorbox environ adjustbox collectbox
      adforn footmisc rsfs tex-gyre txfonts boondox sourcecodepro
  # netlify
  - nvm install stable
  - npm install netlify-cli -g
  ## install fonts
  - mkdir -p ~/.fonts
  - curl -fLo Adobe-Fonts.zip https://github.com/XiangyunHuang/fonts/releases/download/v0.1/Adobe-Fonts.zip
  - unzip Adobe-Fonts.zip -d ~/.fonts/adobe
  - fc-cache -fsv
  # MSG
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - echo $COMMIT_MSG
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - echo $DEPLOY_MSG
  - chmod +x ./_deploy_error

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE, checkBuilt = TRUE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "all")'

deploy:
  - provider: script
    script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: 
        - master
        - devel
    local_dir: _book

after_failure:
  - tlmgr --version
  - tlmgr info elegantbook
  - tlmgr info --list --only-installed --data name
  - ./_deploy_error
  # 最好此时把所有文件推送到新的分支 error
