#!/bin/sh

set -e

[ -z "${GITHUB_TOKEN}" ] && exit 0
[ "${TRAVIS_BRANCH}" != "master" ] && exit 0

git checkout -b error
git add --all *
git commit -m"report error by (travis build ${TRAVIS_BUILD_NUMBER})"
git push -q -f origin error
