--- 
title: "Elegant Bookdown Template"
subtitle: "优雅的 Bookdown 书籍模版"
author: 
  - 黄湘云
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: elegantbook
bibliography: 
 - book.bib
 - packages.bib
lot: yes
lof: yes
colorlinks: yes
link-citations: yes
github-repo: XiangyunHuang/ElegantBookdown
classoption: "cn,11pt,chinese,bibstyle=apalike"
description: "This is a bookdown template based on ElegantBook. The output format for this template is bookdown::gitbook and bookdown::pdf_book."
---

\mainmatter

# 欢迎 {#welcome}

```{r,include=FALSE}
source('_common.R')
```

> A Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.  
> 
> --- John Gruber

这是一份 R Markodwn 文档。 Markdown 提供一种简洁的格式语法，支持数学公式 $\alpha$ 和 $\beta$，用来生成 HTML、PDF 和 MS Word 文档。

当你点击 **Knit** 按钮时，就会生成一份包含正文和代码执行结果的文档。你可以像这样嵌入 R 代码块：

```{r cars}
summary(cars)
```

## 运行环境 {#session-info}

```{r}
xfun::session_info(c("rmarkdown", "bookdown", "knitr"), dependencies = FALSE)
```


```{r, echo=FALSE}
# modified from https://github.com/hadley/adv-r/blob/4915e2984168da50671491db238d351e5590c07b/Introduction.Rmd#L264
ruler <- function(width = getOption("width")) {
  x <- seq_len(width)
  y <- ifelse(x %% 10 == 0, as.character((x %/% 10) %% 10),
    ifelse(x %% 5 == 0, "+", "-")
  )
  cat(y, "\n", sep = "")
  cat(x %% 10, "\n", sep = "")
}
```
```{r, comment=NA}
ruler()
```


```{r include=FALSE,cache=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
