on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron:  '0 11 * * 1'

name: bookdown

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    env:
      LANG: "en_US.UTF-8"
      TZ: "Asia/Shanghai"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.1'

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install LaTeX Packages
        run: |
          tinytex::tlmgr_install(readLines("texlive.txt"))
          tinytex::tl_pkgs()
        shell: Rscript {0}

      - name: Render Book
        id: render-book
        run: |
          res <- bookdown::render_book("index.Rmd", "all")
          cat(sprintf("::set-output name=dir::%s", dirname(res)))
        shell: Rscript {0}

      - name: Upload book folder for debug
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: Upload Book
          path: _book

      # 先本地创建一个 Github Pages 分支推送上来才行
      # https://bookdown.org/yihui/bookdown/github.html
      - name: Checkout the gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: book-output

      - name: Deploy to Github Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./_deploy.sh
